project:
  type: website
  render:
    - slides/index.qmd
    - tutorial/index.qmd
    - app/index.qmd
    - index.qmd
website:
  title: hmetad
  site-path: /hmetad_workshop/
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tutorial/index.html
        text: Tutorial
      - href: slides/index.html
        text: Slides
        target: _blank
      - href: https://kevingoneill.shinyapps.io/hmetad
        text: App
        target: _blank
      - href: https://metacoglab.github.io/hmetad/
        text: Documentation
        target: _blank

format:
  html:
    theme:
      - simplex
    toc: false


