---
title: "The meta-d' model of confidence ratings"
format: html
server: shiny
page-layout: custom
---


```{r}
#| include: false
library(bslib)
```

```{r}
#| include: false
#| context: server
library(distributional)
library(ggdist)
library(ggplot2)
library(tidyr)
library(dplyr)
library(purrr)
library(paletteer)
library(patchwork)
library(hmetad)

ALPHA <- .33
PALETTE <- paletteer_d("fishualize::Phractocephalus_hemioliopterus")[c(1, 3)]
DIST_COLOR <- paletteer_d("fishualize::Phractocephalus_hemioliopterus")[4]
DELTA_COLOR <- paletteer_d("fishualize::Phractocephalus_hemioliopterus")[2]

THEME_SDT <- function(xlab='Evidence', limits=c(-2.5, 2.5), base_size=18,
                      expand=expansion(mult=c(.1, .1))) {
  list(scale_x_continuous(xlab, limits=limits, breaks=seq(-4, 4, by=2), expand=expand),
       scale_color_manual('Stimulus', values=PALETTE),
       scale_fill_manual('Stimulus', values=PALETTE),
       scale_y_continuous(expand=c(0, 0)),
       theme_classic(base_size=base_size),
       theme(axis.title.y=element_blank(),
             axis.text.y=element_blank(),
             axis.ticks.y=element_blank(),
             axis.line.y=element_blank()))
}
```

```{r}
#| panel: sidebar
sliderInput("d", "Type 1 sensitivity (d')",
  min=0, max=5, value=1.5, step=.01)
sliderInput("c", "Type 1 response bias (c)",
  min=-2, max=2, value=0, step=.01)
sliderInput("metad", "Type 2 sensitivity (meta-d')",
  min=0, max=5, value=1.5, step=.01)
sliderInput("metac2_0_1", "Type 2 response bias (meta-c2-0-1-diff)",
  min=0, max=1.5, value=.75, , step=.01)
sliderInput("metac2_0_2", "Type 2 response bias (meta-c2-0-2-diff)",
  min=0, max=1.5, value=.75, step=.01)
sliderInput("metac2_1_1", "Type 2 response bias (meta-c2-1-1-diff)",
  min=0, max=1.5, value=.75, step=.01)
sliderInput("metac2_1_2", "Type 2 response bias (meta-c2-0-2-diff)",
  min=0, max=1.5, value=.75, step=.01)
```

```{r}
#| panel: fill
plotOutput('type1')
plotOutput('type2')
navset_pill(
  nav_panel('Joint Distribution', plotOutput('joint_response')),
  nav_panel('Pseudo Type 1 ROC/Type 2 ROC', plotOutput('roc'))
)
```

```{r}
#| context: server
## set SDT distributions
evidence <- reactive({
  tibble(stimulus=factor(0:1),
    d_prime=input$d, c=input$c, meta_d_prime=input$metad,
    mu1=c(-1, 1)*d_prime/2, sd=1,
    mu2=c(-1, 1)*meta_d_prime/2)
})

# set type 2 criteria
c2_0 <- reactive({
  input$c - cumsum(c(input$metac2_0_1, input$metac2_0_2))
})
c2_1 <- reactive({
  c2_1 <- input$c + cumsum(c(input$metac2_1_1, input$metac2_1_2))
})

# joint type 1/type 2 response probabilities
joint_prob <- reactive({
  K <- 3
  tibble(stimulus=rep(0:1, each=6),
    response=rep(0:1, each=K, times=2),
    confidence=rep(c(rev(seq_len(K)), seq_len(K)), times=2),
    p=c(metad_pmf(0, input$d, input$c, input$metad, input$c, c2_0(), c2_1()),
      metad_pmf(1, input$d, input$c, input$metad, input$c, c2_0(), c2_1()))) |>
    mutate(stimulus=factor(stimulus, levels=0:1),
      joint_response=factor(as.integer(ifelse(response,
        confidence + K,
        K + 1 - confidence)),
        levels=1:(2*K)),
      response=factor(response, levels=0:1),
      confidence=factor(confidence, levels=1:K))
})

output$type1 <- renderPlot({
  ggplot(evidence(), aes(xdist=dist_normal(mu1, sd))) +
    stat_slab(aes(fill=stimulus), color=NA, alpha=ALPHA, scale=.8, show.legend=FALSE) +
    geom_vline(aes(xintercept=c)) +
    THEME_SDT(xlab='Type 1 Evidence', expand=expansion())
})

output$type2 <- renderPlot({
  p.type2.0 <- ggplot(evidence(), aes(xdist=dist_truncated(dist_normal(mu2, sd), upper=c))) +
    stat_slab(aes(fill=stimulus), color=NA, alpha=ALPHA, scale=.8, show.legend=FALSE) +
    geom_vline(xintercept=input$c) +
    geom_vline(aes(xintercept=x), data=tibble(x=c2_0())) +
    THEME_SDT(xlab='Type 2 Evidence\n("0" Response)', limits=c(-2.5, input$c),
      expand=expansion(add=c(0, 0.01)))
  p.type2.1 <- ggplot(evidence(), aes(xdist=dist_truncated(dist_normal(mu2, sd), lower=c))) +
    stat_slab(aes(fill=stimulus), color=NA, alpha=ALPHA, scale=.8, show.legend=FALSE) +
    geom_vline(xintercept=input$c) +
    geom_vline(aes(xintercept=x), data=tibble(x=c2_1())) +
    THEME_SDT(xlab='Type 2 Evidence\n("1" Response)', limits=c(input$c, 2.5),
      expand=expansion(add=c(.01, 0)))

  offset <- (input$c+2.5) / 5
  
  (p.type2.0 | p.type2.1) +
    plot_layout(widths=c(offset, 1-offset))
})

output$joint_response <- renderPlot({
  ggplot(joint_prob(), aes(x=joint_response, y=p, group=stimulus, fill=stimulus)) +
    geom_col(position=position_dodge(.925)) +
    scale_x_discrete(labels=c('Confident\n"0"', '', 'Guess\n"0"',
      'Guess\n"1"', '', 'Confident\n"1"')) +
    scale_fill_manual('Stimulus', values=PALETTE) +
    theme_classic(18) +
    theme(axis.title=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks.y=element_blank(),
      axis.line.y=element_blank(),
      legend.position='bottom')
})

output$roc <- renderPlot({
  roc1 <- joint_prob() |>
    pivot_wider(names_from=stimulus, values_from=p, names_prefix='p_') |>
    mutate(p_hit=1-cumsum(p_1),
      p_fa=1-cumsum(p_0)) |>
    complete(tibble(p_hit=1, p_fa=1)) |>
    ggplot(aes(x=p_fa, y=p_hit)) +
    geom_abline(intercept=0, slope=1, linetype='dashed') +
    geom_line() +
    geom_point() +
    coord_fixed(xlim=c(0, 1), ylim=c(0, 1)) +
    xlab('P(Hit)') + ylab('P(False Alarm)') +
    theme_bw(18) +
    theme(panel.grid=element_blank())

  roc2 <- joint_prob() |>
    mutate(correct=as.integer(response==stimulus)) |>
    select(-joint_response, -stimulus) |>
    pivot_wider(names_from=correct, values_from=p, names_prefix='p_') |>
    group_by(response) |>
    arrange(confidence) |>
    mutate(p_1=p_1/sum(p_1),
      p_0=p_0/sum(p_0),
      p_hit2=1-cumsum(p_1),
      p_fa2=1-cumsum(p_0),
      response=factor(response, levels=0:1, labels=c('"0"', '"1"'))) |>
    complete(tibble(p_hit2=1, p_fa2=1)) |>
    ggplot(aes(x=p_fa2, y=p_hit2, color=response)) +
    geom_abline(intercept=0, slope=1, linetype='dashed') +
    geom_point() +
    geom_line() +
    coord_fixed(xlim=c(0, 1), ylim=c(0, 1), expand=FALSE) +
    xlab('P(Confidence ≥ k | Incorrect)') + ylab('P(Confidence ≥ k | Correct)') +
    theme_bw(18) +
    theme(panel.grid=element_blank())

  roc1 | roc2    
})
```
